import './index.css.proxy.js';
/* src/routes/index.svelte generated by Svelte v3.30.1 */
import {
	HtmlTag,
	SvelteComponent,
	detach,
	empty,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../web_modules/svelte/internal.js";

import { FRONTMATTER, HTML } from "../content/README.js";

function create_fragment(ctx) {
	let html_tag;
	let html_anchor;

	return {
		c() {
			html_anchor = empty();
			html_tag = new HtmlTag(html_anchor);
		},
		m(target, anchor) {
			html_tag.m(HTML, target, anchor);
			insert(target, html_anchor, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(html_anchor);
			if (detaching) html_tag.d();
		}
	};
}

class Routes extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Routes;